---
- name: Check and Restart HTTPD if needed
  hosts: all  
  become: yes  # Run tasks with root privileges

  tasks:
    - name: Check HTTPD status
      systemd:
        name: httpd
        state: status
      register: httpd_status

    - name: Restart HTTPD if not active
      systemd:
        name: httpd
        state: restarted
      when: httpd_status.status != 'active'
