---
- name: Ensure SSHD is running
  hosts: all
  become: true
  tasks:
    - name: Check SSHD status
      shell: systemctl status sshd
      register: sshd_status
      ignore_errors: true

    - name: Restart SSHD if not running
      systemd:
        name: sshd
        state: restarted
      when: sshd_status.rc != 0
      
    - name: cat
      shell: "cat /tmp/smp"
      register: cat_a
      ignore_errors: true
      
    - name: Print the contents of /tmp/smp
      debug:
        var: cat_a.stdout
